### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by jafkc2** [moehreag/legacy-lwjgl3#2]
Using the ornithe branch, the game crashes at launch.

System:
* Arch linux
* KDE Plasma 5.27.10 Wayland

Tested with Java 8 and Java 17

Error:

```
Description: Displaying init error screen

java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_4976084
    at io.github.moehreag.legacylwjgl3.DesktopFileInjector.setIcon(DesktopFileInjector.java:51)
    at org.lwjgl.opengl.Display.setIcon(Display.java:111)
    at net.minecraft.class_1600.method_9401(class_1600.java:560)
    at net.minecraft.class_1600.displayInitErrorScreen(class_1600.java:11783)
    at net.minecraft.class_1600.method_5580(class_1600.java:11542)
    at net.minecraft.client.main.Main.main(Main.java:124)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.minecraft.unmapped.C_4976084
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 9 more
```

**Comment by moehreag** [comment]
Could you please attach the entire crash log? Thanks!

**Comment by jafkc2** [comment]
```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2023-12-22 19:56:17 BRT
Description: Displaying init error screen

java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_4976084
    at io.github.moehreag.legacylwjgl3.DesktopFileInjector.setIcon(DesktopFileInjector.java:51)
    at org.lwjgl.opengl.Display.setIcon(Display.java:111)
    at net.minecraft.class_1600.method_9401(class_1600.java:560)
    at net.minecraft.class_1600.displayInitErrorScreen(class_1600.java:11783)
    at net.minecraft.class_1600.method_5580(class_1600.java:11542)
    at net.minecraft.client.main.Main.main(Main.java:124)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.minecraft.unmapped.C_4976084
    at java.lang.ClassLoader.findClass(ClassLoader.java:523)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 9 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Linux (amd64) version 6.6.7-zen1-1-zen
    Java Version: 1.8.0_372, Temurin
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
    Memory: 352108528 bytes (335 MB) / 594018304 bytes (566 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 18 total; -Xmx3072M -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+AggressiveOpts -XX:MaxInlineLevel=15 -XX:MaxVectorSize=32 -XX:ThreadPriorityPolicy=1 -XX:+UseNUMA -XX:+UseDynamicNumberOfGCThreads -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=350M -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Suspected Mods: Fabric Loader (fabricloader), Legacy LWJGL3 (legacy-lwjgl3), Minecraft (minecraft)
    Fabric Mods: 
        axolotlclient: AxolotlClient 3.0.4+1.8.9
        axolotlclient-common: AxolotlClient (Common) 3.0.4
        axolotlclientconfig: AxolotlClientConfig 2.1.13+1.8.9
        com_velocitypowered_velocity-native: velocity-native 4.0.0-SNAPSHOT
        fabricloader: Fabric Loader 0.14.23
        io_github_axolotlclient_axolotlclient-config_axolod6a22e2119cdc0: AxolotlClientConfig-common 2.1.9
        io_github_axolotlclient_axolotlclient-config_common_: common 2.1.13
        java: OpenJDK 64-Bit Server VM 8
        languagefix: LanguageFix 1.0.0+1.8.9_to_1.12.2
        legacy-fabric-api: Legacy Fabric API 1.9.0
        legacy-fabric-api-base: Legacy Fabric API Base 1.1.0+1.8.9+f368a06d39
        legacy-fabric-api-base-common: Legacy Fabric API Base Common 1.1.0+1dd3cad892
        legacy-fabric-command-api-v1: Legacy Fabric Command API (V1) 1.0.0+ae4aa0d092
        legacy-fabric-command-api-v2: Legacy Fabric Command API (v2) 1.0.0+1.8.9+01f7587839
        legacy-fabric-crash-report-info-v1: Legacy Fabric Crash Report Info (v1) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-entity-events-v1: Legacy Fabric Entity Events (V1) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-entity-events-v1-common: Legacy Fabric Entity Events (V1) 1.0.0+ae4aa0d092
        legacy-fabric-fixes: Legacy Fabric Fixes 1.0.0+1.8.9+f368a06d39
        legacy-fabric-gamerule-api-v1: Fabric Gamerule API (v1) 1.0.0+ae4aa0d092
        legacy-fabric-item-groups-v1: Legacy Fabric Item Groups (V1) 2.0.0+1.8.9+f368a06d39
        legacy-fabric-item-groups-v1-common: Legacy Fabric Item Groups (V1) 2.0.0+1dd3cad892
        legacy-fabric-keybinding-api-v1-common: Legacy Fabric Keybinding API (V1) 1.0.0+ae4aa0d092
        legacy-fabric-lifecycle-events-v1: Legacy Fabric Lifecycle Events (V1) 1.0.1+1.8.9+d86bee7939
        legacy-fabric-lifecycle-events-v1-common: Legacy Fabric Lifecycle Events (V1) 1.0.1+ae4aa0d092
        legacy-fabric-logger-api-v1: Legacy Fabric Logger API (v1) 1.0.4+ae4aa0d092
        legacy-fabric-networking-api-v1: Legacy Fabric Networking API (v1) 2.0.0+1.8.9+01f7587839
        legacy-fabric-networking-api-v1-common: Legacy Fabric Networking API (v1) 2.0.0+022f9a7592
        legacy-fabric-permissions-api-v1: Legacy Fabric Permissions API (v2) 1.0.0+1.8.9+f368a06d39
        legacy-fabric-permissions-api-v1-common: Legacy Fabric Permissions API (v1) 1.0.0+ae4aa0d092
        legacy-fabric-registry-sync-api-v1: Legacy Fabric Registry Sync API (V1) 2.1.0+1.8.9+508c546039
        legacy-fabric-registry-sync-api-v1-common: Legacy Fabric Registry Sync API (V1) 2.1.0+508c546092
        legacy-fabric-rendering-api-v1: Legacy Fabric Rendering API (V1) 1.0.0+1.8.9+022f9a7539
        legacy-fabric-rendering-api-v1-common: Legacy Fabric Rendering API (V1) 1.0.0+ae4aa0d092
        legacy-fabric-resource-loader-v1: Legacy Fabric Resource Loader (V1) 2.1.0+1.8.9+022f9a7539
        legacy-fabric-resource-loader-v1-common: Legacy Fabric Resource Loader (V1) Common 2.1.0+a9c128f492
        legacy-lwjgl3: Legacy LWJGL3 1.1.4
        legacyclientcommands: Legacy Client Commands 1.0.0
        legacyenhance: LegacyEnhance 1.0.0
        legacyvanillafix: Legacy VanillaFix 1.0.9+1.8.x
        minecraft: Minecraft 1.8.9
        mm: Manningham Mills 2.0
        modmenu: Mod Menu 1.1.0
        oldblockhit: Old Block Hit 0.2.2
        optifabric: Optifabric 1.0.5+1.8.9
        org_slf4j_slf4j-api: slf4j-api 1.7.30
        org_slf4j_slf4j-simple: slf4j-simple 1.7.30
        org_zeroturnaround_zt-zip: zt-zip 1.14
        saltlib: SaltLib 0.3.0
        search-in-resources: Search in Resources 1.0.1
```

**Comment by moehreag** [comment]
You're using legacyfabric. In this case, I have good news! You can download a version of AxolotlClient for ornithe (including some preview features for the next release) here: https://github.com/moehreag/AxolotlClient-mod/actions/runs/7238742985 . You will also have to install ornithe from https://ornithemc.github.io though. In case you prefer to stay on legacyfabric for now, you can also use this repository's `main` branch (although it is considerably behind the ornithe branch). There's a download available here: https://moehreag.duckdns.org/maven/releases/com/github/zarzelcow/legacy-lwjgl3/1.1.1/legacy-lwjgl3-1.1.1-all-remapped.jar (note that all later versions are for ornithe)

**Comment by jafkc2** [comment]
Oh, I did not know that... Thanks, I will try it out
