### ISSUE TITLE
1.12.2 crash on startup

### ISSUE THREAD

**Issue by Dainternetdude** [moehreag/legacy-lwjgl3#3]
Minecraft 1.12.2 crashes on startup.

Mods:
- legacy-fabric-api-1.9.1
- legacy-lwjgl-1.1.5
- ornithe-standard-libraries-0.12.0

Official launcher. Legacy Fabric loader 0.15.3. macOS 13.6 (Intel). I have never used this mod or legacy fabric before (init issue?). When I tested with 1.8.9 it seemed to be the same thing. Sounds like you're on Linux so if you think this is a mac-specific issue and you need my help debugging it please reach out to me on Discord.

```
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'client-init' due to errors, provided by 'osl-config'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'client-init' due to errors, provided by 'osl-config'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.minecraft.client.main.Main.handler$zcl000$osl-entrypoints$osl$entrypoints$init(Main.java:529)
	at net.minecraft.client.main.Main.main(Main.java)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	... 2 more
	Suppressed: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_8105098
		at net.ornithemc.osl.networking.impl.Networking.initClient(Networking.java:39)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 5 more
	Caused by: java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_8105098
		... 7 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.unmapped.C_8105098
		at java.lang.ClassLoader.findClass(ClassLoader.java:530)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 7 more
	Suppressed: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_8105098
		at net.ornithemc.osl.resource.loader.impl.ResourceLoader.initClient(ResourceLoader.java:31)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 5 more
	Caused by: java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_8105098
		... 7 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.unmapped.C_8105098
		at java.lang.ClassLoader.findClass(ClassLoader.java:530)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 7 more
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_8105098
	at net.ornithemc.osl.config.impl.client.ClientConfigInitializer.initClient(ClientConfigInitializer.java:13)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_8105098
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.unmapped.C_8105098
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
<img width="912" alt="Screenshot 2024-01-14 at 10 54 18 AM" src="https://github.com/moehreag/legacy-lwjgl3/assets/53956237/2fdc77f3-8145-4483-8222-80c88d1a9f32">

Thanks for your work.

**Comment by moehreag** [comment]
Please install ornithe from https://ornithemc.net. Note that Ornithe mods are **not compatible** with legacyfabric mods as they use different intermediaries.

**Comment by Dainternetdude** [comment]
Thanks but may I ask, what is Ornithe? The website doesn't give a lot of information. Is this a mod or a mod loader or something else?

**Comment by moehreag** [comment]
> Thanks but may I ask, what is Ornithe? The website doesn't give a lot of information. Is this a mod or a mod loader or something else?

Ornithe is an organization providing intermediaries and tooling for fabric & quilt to run on legacy versions of the game.

**Comment by Dainternetdude** [comment]
Still crashes on startup. Minecraft 1.12.2. Ornithe universal installer 0.10.1. Mods list:
- legacy-lwjgl3-1.1.7+1.8.9
- ornithe-standard-libraries-1.13.3
```
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: net.minecraft.unmapped.C_6517019.m_4031679(Ljava/lang/String;Ljava/util/concurrent/Callable;)V
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: net.minecraft.unmapped.C_6517019.m_4031679(Ljava/lang/String;Ljava/util/concurrent/Callable;)V
	at net.minecraft.unmapped.C_8105098.m_8470592(C_8105098.java:3632)
	at net.minecraft.unmapped.C_8105098.m_7986397(C_8105098.java:408)
	at net.minecraft.client.main.Main.main(Main.java:123)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	... 2 more
```
<img width="912" alt="Screenshot 2024-02-16 at 6 53 25 PM" src="https://github.com/moehreag/legacy-lwjgl3/assets/53956237/12b511b8-3c4f-4505-b97f-990ac16abc43">

**Comment by moehreag** [comment]
Could you please provide a full log? I am unable to reproduce a crash on 1.12.2 with OSL 0.13.3 and version 1.1.7+1.8.9 of this mod.

**Comment by Dainternetdude** [comment]
[latest.log](https://github.com/moehreag/legacy-lwjgl3/files/14398990/latest.log)
