### ISSUE TITLE
Minecraft crashes immediately when it comes up.

### ISSUE THREAD

**Issue by ghost** [moehreag/legacy-lwjgl3#4]
Minecraft 1.8.9 crashes when it start.

Mods:
legacy-fabric-api 1.9.1
legacy-lwjgl3 1.1.5+1.2.5

Hello.
I use xmcl launcher and due to the problem of Nvidia (can't switch between two graphics) I have to set these two variables:
```
export __VK_LAYER_NV_optimus="NVIDIA_only"
export __GLX_VENDOR_LIBRARY_NAME=nvidia
```
But these variables cause havoc in xorg. I came to Wayland and there was no problem there, but another problem occurred that caused the game to not work properly in Wayland.
So, I installed this mod, but when the game is launched, it immediately crashes:
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/4/24 7:46 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraft/unmapped/C_9236886
	at io.github.moehreag.legacylwjgl3.util.TextureUtil.<clinit>(TextureUtil.java:19)
	at io.github.moehreag.legacylwjgl3.implementation.glfw.VirtualGLFWMouseImplementation.loadCursor(VirtualGLFWMouseImplementation.java:345)
	at io.github.moehreag.legacylwjgl3.implementation.glfw.VirtualGLFWMouseImplementation.setup(VirtualGLFWMouseImplementation.java:168)
	at io.github.moehreag.legacylwjgl3.implementation.glfw.VirtualGLFWMouseImplementation.lambda$createMouse$1(VirtualGLFWMouseImplementation.java:92)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at org.lwjgl.opengl.Display.update(Display.java:147)
	at net.minecraft.class_1600.method_9403(class_1600.java:995)
	at net.minecraft.class_1600.method_2916(class_1600.java:944)
	at net.minecraft.class_1600.method_5580(class_1600.java:325)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.minecraft.unmapped.C_9236886
	at java.lang.ClassLoader.findClass(ClassLoader.java:523)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 6.7.0-zen3-1-zen
	Java Version: 1.8.0_402, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 306871040 bytes (292 MB) / 659030016 bytes (628 MB) up to 3679977472 bytes (3509 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Fabric Mods: 
		fabricloader: Fabric Loader 0.15.6
		java: OpenJDK 64-Bit Server VM 8
		legacy-fabric-api: Legacy Fabric API 1.9.1
		legacy-fabric-api-base: Legacy Fabric API Base 1.1.0+1.8.9+f368a06d39
		legacy-fabric-api-base-common: Legacy Fabric API Base Common 1.1.0+1dd3cad892
		legacy-fabric-command-api-v1: Legacy Fabric Command API (V1) 1.0.0+ae4aa0d092
		legacy-fabric-command-api-v2: Legacy Fabric Command API (v2) 1.0.0+1.8.9+01f7587839
		legacy-fabric-crash-report-info-v1: Legacy Fabric Crash Report Info (v1) 1.0.0+1.8.9+f368a06d39
		legacy-fabric-entity-events-v1: Legacy Fabric Entity Events (V1) 1.0.0+1.8.9+f368a06d39
		legacy-fabric-entity-events-v1-common: Legacy Fabric Entity Events (V1) 1.0.0+ae4aa0d092
		legacy-fabric-gamerule-api-v1: Fabric Gamerule API (v1) 1.0.0+ae4aa0d092
		legacy-fabric-item-groups-v1: Legacy Fabric Item Groups (V1) 2.0.0+1.8.9+f368a06d39
		legacy-fabric-item-groups-v1-common: Legacy Fabric Item Groups (V1) 2.0.0+1dd3cad892
		legacy-fabric-keybinding-api-v1-common: Legacy Fabric Keybinding API (V1) 1.0.0+ae4aa0d092
		legacy-fabric-lifecycle-events-v1: Legacy Fabric Lifecycle Events (V1) 1.0.1+1.8.9+d86bee7939
		legacy-fabric-lifecycle-events-v1-common: Legacy Fabric Lifecycle Events (V1) 1.0.1+ae4aa0d092
		legacy-fabric-logger-api-v1: Legacy Fabric Logger API (v1) 1.0.4+ae4aa0d092
		legacy-fabric-networking-api-v1: Legacy Fabric Networking API (v1) 2.0.0+1.8.9+01f7587839
		legacy-fabric-networking-api-v1-common: Legacy Fabric Networking API (v1) 2.0.0+022f9a7592
		legacy-fabric-permissions-api-v1: Legacy Fabric Permissions API (v2) 1.0.0+1.8.9+f368a06d39
		legacy-fabric-permissions-api-v1-common: Legacy Fabric Permissions API (v1) 1.0.0+ae4aa0d092
		legacy-fabric-registry-sync-api-v1: Legacy Fabric Registry Sync API (V1) 2.1.0+1.8.9+508c546039
		legacy-fabric-registry-sync-api-v1-common: Legacy Fabric Registry Sync API (V1) 2.1.0+508c546092
		legacy-fabric-rendering-api-v1: Legacy Fabric Rendering API (V1) 1.0.0+1.8.9+022f9a7539
		legacy-fabric-rendering-api-v1-common: Legacy Fabric Rendering API (V1) 1.0.0+ae4aa0d092
		legacy-fabric-resource-loader-v1: Legacy Fabric Resource Loader (V1) 2.1.0+1.8.9+022f9a7539
		legacy-fabric-resource-loader-v1-common: Legacy Fabric Resource Loader (V1) Common 2.1.0+a9c128f492
		legacy-lwjgl3: Legacy LWJGL3 1.1.5+1.2.5
		minecraft: Minecraft 1.8.9
		mixinextras: MixinExtras 0.3.2
	Launched Version: Fabric
	LWJGL: 3.3.2-snapshot
	OpenGL: Mesa Intel(R) Xe Graphics (TGL GT2) GL version 4.6 (Compatibility Profile) Mesa 23.3.3-arch1.1, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 8x 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
```
I think the problem is the design of the cursor in the game.
When I hide the cursor there is no problem, but when I bring the cursor to the game screen, the game immediately crashes.

Thank you for your efforts.

**Comment by moehreag** [comment]
see #3 or #2, it's the same. TL;DR: Use Ornithe from https://ornithemc.net. This should especially not be an issue for you as you aren't using any other mods besides this one.
